<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Store Profile · MotoBook Merchant</title>
    @vite(['resources/css/app.css', 'resources/css/pages/merchant-store.css'])
</head>
<body class="merchant-store-shell" style="--merchant-brand-color: {{ $store->brand_color ?? '#2F9B78' }}">
    <aside class="merchant-sidebar merchant-store-sidebar"><a href="{{ route('merchant.dashboard') }}" class="merchant-brand"><span class="merchant-brand-mark"></span><span><b>Moto</b>Book</span></a><div class="merchant-store-switcher"><span class="merchant-store-kicker">Merchant workspace</span><strong>{{ $store->name }}</strong><span class="merchant-store-status {{ $store->is_open ? 'is-open' : 'is-closed' }}"><span></span>{{ $store->is_open ? 'Open' : 'Closed' }}</span></div><nav class="merchant-nav"><a href="{{ route('merchant.dashboard') }}" class="merchant-nav-link"><span>⌂</span>Dashboard</a><a href="{{ route('merchant.orders.index') }}" class="merchant-nav-link"><span>▤</span>Orders</a><a href="{{ route('merchant.menu.index') }}" class="merchant-nav-link"><span>◈</span>Menu</a><a href="{{ route('merchant.store.edit') }}" class="merchant-nav-link is-active"><span>□</span>Store profile</a><a href="{{ route('merchant.sales.index') }}" class="merchant-nav-link"><span>◒</span>Sales</a></nav><div class="merchant-sidebar-footer"><form method="POST" action="{{ route('logout') }}">@csrf<button type="submit" class="merchant-logout"><span>↪</span>Log out</button></form></div></aside>
    <main class="merchant-store-main"><header class="merchant-store-header"><div><p class="merchant-eyebrow">Brand studio</p><h1>Store profile</h1></div><a href="{{ route('merchant.dashboard') }}" class="merchant-store-back">← Dashboard</a></header><div class="merchant-store-content">@if(session('status'))<div class="merchant-alert">{{ session('status') }}</div>@endif @if($errors->any())<div class="merchant-error">{{ $errors->first() }}</div>@endif
        <div class="merchant-store-layout"><section class="merchant-brand-card"><div class="merchant-form-card-heading"><span class="merchant-overline">Customer-facing identity</span><h2>Make the store feel like yours</h2><p>These details appear on your storefront and menu.</p></div><form method="POST" action="{{ route('merchant.store.update') }}" enctype="multipart/form-data">@csrf @method('PATCH')<div class="merchant-form-field"><label for="name">Restaurant name</label><input id="name" name="name" required value="{{ old('name', $store->name) }}"></div><div class="merchant-form-two"><div class="merchant-form-field"><label for="category">Category</label><input id="category" name="category" required value="{{ old('category', $store->category) }}"></div><div class="merchant-form-field"><label for="phone">Phone</label><input id="phone" name="phone" required value="{{ old('phone', $store->phone) }}"></div></div><div class="merchant-form-field"><label for="address">Address</label><textarea id="address" name="address" rows="3" required>{{ old('address', $store->address) }}</textarea></div><div class="merchant-form-two"><div class="merchant-form-field"><label for="brand_color">Brand color</label><div class="merchant-color-input"><input id="brand_color" name="brand_color" type="color" value="{{ old('brand_color', $store->brand_color ?? '#2F9B78') }}"><input type="text" value="{{ old('brand_color', $store->brand_color ?? '#2F9B78') }}" readonly></div></div><div class="merchant-form-field"><label for="logo">Logo image</label><input id="logo" name="logo" type="file" accept="image/*"></div></div><div class="merchant-form-field"><label for="banner">Store banner image</label><input id="banner" name="banner" type="file" accept="image/*"><small class="merchant-help">Use a wide photo of your restaurant or signature food.</small></div><button class="merchant-form-submit" type="submit">Save store identity <span>→</span></button></form></section>
            <aside class="merchant-brand-preview"><span class="merchant-overline">Live preview</span><div class="merchant-preview-banner" @if($store->banner) style="background-image:url('{{ asset('storage/'.$store->banner) }}')" @endif>@if(!$store->banner)🍽️@endif</div><div class="merchant-preview-body">@if($store->logo)<img src="{{ asset('storage/'.$store->logo) }}" alt="{{ $store->name }}" class="merchant-preview-logo">@else<div class="merchant-preview-logo placeholder">{{ strtoupper(substr($store->name, 0, 1)) }}</div>@endif<h3>{{ $store->name }}</h3><p>{{ $store->category }} · 20-30 min</p><span class="merchant-preview-chip" style="background: {{ $store->brand_color ?? '#2F9B78' }}">Free delivery</span></div></aside>
        </div>
    </div></main>
    <section class="merchant-store-controls">
        <div class="merchant-form-card-heading"><span class="merchant-overline">Operations</span><h2>Availability and delivery location</h2></div>
        <form method="POST" action="{{ route('merchant.store.update') }}">
            @csrf @method('PATCH')<input type="hidden" name="is_open" value="0">
            <label class="merchant-check"><input type="checkbox" name="is_open" value="1" @checked($store->is_open)> Accept customer orders</label>
            <div class="merchant-form-two"><div class="merchant-form-field"><label for="latitude">Latitude</label><input id="latitude" name="latitude" type="number" step="0.0000001" value="{{ old('latitude', $store->latitude) }}" placeholder="e.g. 11.5850"></div><div class="merchant-form-field"><label for="longitude">Longitude</label><input id="longitude" name="longitude" type="number" step="0.0000001" value="{{ old('longitude', $store->longitude) }}" placeholder="e.g. 122.7511"></div></div>
            <div data-location-picker data-latitude-target="latitude" data-longitude-target="longitude">
                <button type="button" class="merchant-form-submit">Use my current location</button>
                <p data-location-status role="status" aria-live="polite"></p>
            </div>
            <button class="merchant-form-submit" type="submit">Save operations settings <span>→</span></button>
        </form>
    </section>
    @include('components.location-picker-script')
    <script>const color = document.getElementById('brand_color'); const colorText = color?.nextElementSibling; color?.addEventListener('input', () => { colorText.value = color.value; });</script>
</body>
</html>
