<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Track delivery · MotoBook</title><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" defer></script>@vite(['resources/css/app.css','resources/css/pages/customer-experience.css'])</head>
<body class="cx-page" data-theme="{{ (auth()->user()->customer_settings['dark_mode'] ?? false) ? 'dark' : 'light' }}"><main class="cx-wrap">
    <header class="cx-topbar"><a class="cx-back" href="{{ route('customer.custom-deliveries.index') }}">‹</a><h1>Track delivery</h1><a class="cx-back" style="margin-left:auto" href="mailto:?subject=Delivery%20help">?</a></header>
    @if(session('status'))<div class="cx-alert">{{ session('status') }}</div>@endif
    <section class="cx-card" style="display:flex;justify-content:space-between;align-items:center;gap:12px"><div><span class="cx-eyebrow">Estimated delivery</span><h2 class="cx-title" style="font-size:21px;margin:5px 0">{{ $customDelivery->status === 'delivered' ? 'Delivered' : ($customDelivery->rider ? 'Rider is on the way' : 'Waiting for a rider') }}</h2></div><span id="delivery-status" class="cx-badge">{{ str_replace('_',' ',$customDelivery->status) }}</span></section>
    <section class="cx-card"><div id="delivery-map" class="cx-map"><div class="cx-map-message">Live rider location will appear here once shared.</div></div>
        <div class="cx-row" style="margin-top:14px"><span class="cx-icon">⌖</span><span class="cx-row-copy"><span class="cx-eyebrow">Pickup location</span><strong>{{ $customDelivery->pickup_address }}</strong><small>{{ $customDelivery->pickup_landmark }}</small></span></div>
        <div class="cx-row" style="margin-top:14px"><span class="cx-icon">●</span><span class="cx-row-copy"><span class="cx-eyebrow">Drop-off / landmark</span><strong>{{ $customDelivery->dropoff_address }}</strong><small>{{ $customDelivery->dropoff_landmark }}</small></span></div>
    </section>
    <section class="cx-card"><div class="cx-eyebrow">Delivery progress</div><div class="cx-tabs" id="progress"><a class="active">Request sent</a><a>Accepted</a><a>Picked up</a><a>Delivered</a></div>
        @if($customDelivery->rider)<div class="cx-row"><span class="cx-icon">♙</span><span class="cx-row-copy"><strong>{{ $customDelivery->rider->user?->name ?? 'Your rider' }}</strong><small>{{ ucfirst($customDelivery->rider->vehicle_type) }} · {{ $customDelivery->rider->plate_number ?: 'MotoBook rider' }}</small></span>@if($customDelivery->rider->user?->phone)<a class="cx-back" href="tel:{{ $customDelivery->rider->user->phone }}">☎</a><a class="cx-back" href="sms:{{ $customDelivery->rider->user->phone }}">☏</a>@endif</div>@else<p class="cx-copy">We’ll notify you when a rider accepts this delivery.</p>@endif
    </section>
    <section class="cx-card"><span class="cx-eyebrow">Payment</span><div class="cx-row" style="margin-top:10px"><span class="cx-icon">{{ $customDelivery->payment_method === 'cod' ? '₱' : 'G' }}</span><span class="cx-row-copy"><strong>{{ $customDelivery->payment_method === 'cod' ? 'Cash on delivery' : 'GCash' }}</strong><small>{{ $customDelivery->payment_method === 'cod' ? 'Amount due to rider' : 'Payment remains pending until confirmed' }}</small></span><strong>₱{{ number_format($customDelivery->total_amount,2) }}</strong></div><hr style="border:0;border-top:1px solid var(--cx-line);margin:18px 0"><div class="cx-row"><span class="cx-icon">✓</span><span class="cx-row-copy"><strong>MotoBook delivery protection</strong><small>Keep your request number and contact support if your package needs attention.</small></span></div></section>
    @if(in_array($customDelivery->status,['pending_assignment','assigned'],true))<form method="POST" action="{{ route('customer.custom-deliveries.cancel',$customDelivery) }}" onsubmit="return confirm('Cancel this delivery request?')">@csrf<button class="cx-button danger" type="submit">Cancel request</button></form>@endif
    <a class="cx-button secondary" style="margin-top:10px" href="{{ route('customer.custom-deliveries.index') }}">All custom deliveries</a>
</main>@include('customer.partials.bottom-nav',['active'=>'orders'])
<script>
document.addEventListener('DOMContentLoaded',()=>{let map,marker,pickup,dropoff;const status=document.getElementById('delivery-status');const coordinates={pickup:[{{ $customDelivery->pickup_latitude ?? 'null' }},{{ $customDelivery->pickup_longitude ?? 'null' }}],dropoff:[{{ $customDelivery->dropoff_latitude ?? 'null' }},{{ $customDelivery->dropoff_longitude ?? 'null' }}]};function setup(){if(!window.L)return;const points=[coordinates.pickup,coordinates.dropoff].filter(p=>p[0]!==null&&p[1]!==null);if(points.length===0)return;map=L.map('delivery-map',{scrollWheelZoom:false}).setView(points[0],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);if(coordinates.pickup[0]!==null)pickup=L.marker(coordinates.pickup).addTo(map).bindPopup('Pickup');if(coordinates.dropoff[0]!==null)dropoff=L.marker(coordinates.dropoff).addTo(map).bindPopup('Drop-off');if(points.length>1)map.fitBounds(points,{padding:[24,24]});document.querySelector('.cx-map-message')?.remove();}setup();async function refresh(){try{const r=await fetch(@json(route('customer.custom-deliveries.tracking',$customDelivery)),{headers:{Accept:'application/json'}});if(!r.ok)return;const data=await r.json();status.textContent=data.status.replaceAll('_',' ');if(data.rider?.latitude&&data.rider?.longitude&&window.L){const p=[data.rider.latitude,data.rider.longitude];if(!map){map=L.map('delivery-map').setView(p,14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);}if(!marker)marker=L.marker(p).addTo(map).bindPopup(data.rider.name||'Rider');else marker.setLatLng(p);}}catch(e){}}setInterval(refresh,12000);});
</script></body></html>
