<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sales · MotoBook Merchant</title>
    @vite(['resources/css/app.css', 'resources/css/pages/merchant-sales.css'])
</head>
<body class="merchant-sales-shell">
    <aside class="merchant-sidebar merchant-sales-sidebar"><a href="{{ route('merchant.dashboard') }}" class="merchant-brand"><span class="merchant-brand-mark"></span><span><b>Moto</b>Book</span></a><div class="merchant-store-switcher"><span class="merchant-store-kicker">Merchant workspace</span><strong>{{ $store->name }}</strong><span class="merchant-store-status {{ $store->is_open ? 'is-open' : 'is-closed' }}"><span></span>{{ $store->is_open ? 'Open' : 'Closed' }}</span></div><nav class="merchant-nav"><a href="{{ route('merchant.dashboard') }}" class="merchant-nav-link"><span>⌂</span>Dashboard</a><a href="{{ route('merchant.orders.index') }}" class="merchant-nav-link"><span>▤</span>Orders</a><a href="{{ route('merchant.menu.index') }}" class="merchant-nav-link"><span>◈</span>Menu</a><a href="{{ route('merchant.store.edit') }}" class="merchant-nav-link"><span>□</span>Store profile</a><a href="{{ route('merchant.sales.index') }}" class="merchant-nav-link is-active"><span>◒</span>Sales</a></nav><div class="merchant-sidebar-footer"><form method="POST" action="{{ route('logout') }}">@csrf<button type="submit" class="merchant-logout"><span>↪</span>Log out</button></form></div></aside>
    <main class="merchant-sales-main"><header class="merchant-sales-header"><div><p class="merchant-eyebrow">Performance</p><h1>Sales report</h1></div><a href="{{ route('merchant.dashboard') }}" class="merchant-sales-back">← Dashboard</a></header><div class="merchant-sales-content">
        <div class="merchant-sales-toolbar"><div><span class="merchant-overline">{{ $store->name }}</span><h2>Revenue at a glance</h2></div><div class="merchant-sales-actions"><a href="{{ route('merchant.sales.index', ['days' => $days, 'format' => 'csv']) }}">Download CSV</a><form method="GET"><label for="days">Period</label><select id="days" name="days" onchange="this.form.submit()"><option value="7" @selected($days === 7)>Last 7 days</option><option value="30" @selected($days === 30)>Last 30 days</option><option value="90" @selected($days === 90)>Last 90 days</option></select></form></div></div>
        <section class="merchant-sales-stat-grid"><article><span>Total sales</span><strong>₱{{ number_format($totalSales, 2) }}</strong><small>Completed and active orders</small></article><article><span>Orders</span><strong>{{ number_format($orderCount) }}</strong><small>Orders in this period</small></article><article><span>Average order</span><strong>₱{{ number_format($averageOrder, 2) }}</strong><small>Average basket value</small></article></section>
        <section class="merchant-sales-grid"><div class="merchant-sales-panel merchant-sales-chart"><div class="merchant-sales-panel-head"><div><span class="merchant-overline">Daily performance</span><h3>Sales trend</h3></div><span class="merchant-sales-legend"><i></i>Revenue</span></div><div class="merchant-sales-plot"><div class="merchant-sales-bars">@php $maxSales = max(1, $dailySales->max('sales')); @endphp @foreach($dailySales as $day)<div class="merchant-sales-bar-column"><div class="merchant-sales-bar" style="height: {{ max(3, ($day['sales'] / $maxSales) * 100) }}%" title="₱{{ number_format($day['sales'], 2) }}"></div><span>{{ $day['label'] }}</span></div>@endforeach</div></div></div><div class="merchant-sales-panel merchant-top-items"><div class="merchant-sales-panel-head"><div><span class="merchant-overline">Best performers</span><h3>Top menu items</h3></div></div>@forelse($topItems as $item)<div class="merchant-sales-item"><span><strong>{{ $item['name'] }}</strong><small>{{ $item['quantity'] }} sold</small></span><b>₱{{ number_format($item['revenue'], 2) }}</b></div>@empty<div class="merchant-sales-empty">No item sales in this period.</div>@endforelse</div></section>
    </div></main>
</body>
</html>
